### ISSUE TITLE
Add links to other years for the current board

### ISSUE THREAD

**Issue by jonashogstrom** [jhogstrom/aoc-highscores2#9]
for easy navigation from 2021 to 2020 etc

**Comment by jhogstrom** [comment]
I started this one. Will work perfectly once I either add the guid to the url or store the last used guid locally. 
However - will there be data for all years? Currently not. We can always request it and/or create for all years when a board is added. Otherwise we need to keep track of whether the data is available and ask for it.

**Comment by jonashogstrom** [comment]
would it help to have the guid in the json data?
If the app handles that the data is not available, sends a message to the API/Queue to refresh and informs the user it should be a rare problem.

**Comment by jhogstrom** [comment]
No need to put the guid in the data. I will have it available from the query params. I just need to handle that better than today and store it somewhere central. And indeed, some better handling of data not (yet) available is on the list. Hopefully will fix at least the guid handling later today.
